apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: dev
spec:
  limits:
    - default:
        memory: 256Mi
        cpu: "500m"
      defaultRequest:
        memory: 128Mi
        cpu: "250m"
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: staging
spec:
  limits:
    - default:
        memory: 512Mi
        cpu: "1"
      defaultRequest:
        memory: 256Mi
        cpu: "500m"
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: prod
spec:
  limits:
    - default:
        memory: 1024Mi
        cpu: "2"
      defaultRequest:
        memory: 512Mi
        cpu: "1"
      type: Container