apiVersion: v1
kind: Service
metadata:
  name: frontend-prod-nodeport
  namespace: prod
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
